
const STORAGE_KEY="taskKanrinnerV1";
const $=id=>document.getElementById(id);
const els={};
["mobileMenuButton","boardNameInput","addBoardButton","boardList","todayButton","homeButton","archiveButton","freeboardButton","settingsButton","todayView","homeView","boardView","archiveView","freeboardView","currentBoardTitle","addSectionButton","addCardButton","completeSelectedButton","deleteBoardButton","searchInput","tagFilter","statusFilter","sortSelect","selectionBar","selectionCountText","clearSelectionButton","completeSelectedBarButton","sectionBoard","openTaskCount","todayTaskCount","overdueCount","monthlyDoneCount","upcomingList","todayList","archiveSearchInput","archiveBoardFilter","archiveList","freeCanvas","addFreeNoteButton","freeImageInput","clearFreeboardButton","cardModal","settingsModal","cardModalTitle","cardTypeInput","cardSectionInput","cardTitleInput","cardContentInput","cardDueInput","cardTagsInput","cardColorInput","cardImageInput","cardLinkInput","repeatTypeInput","repeatIntervalWrap","repeatIntervalInput","weekdayPickerWrap","imagePreviewWrap","imagePreview","removeImageButton","saveCardButton","themeSelect","accentColorInput","densitySelect","installAppButton","exportButton","importInput"].forEach(id=>els[id]=$(id));

let editingCardId=null,editingImageData="",draggedCardId=null;

function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function defaultData(){
 const bid=uid(),sid=uid();
 return {view:"board",selectedBoardId:bid,settings:{theme:"normal",accent:"#2563eb",density:"normal"},
 boards:[
  {id:bid,name:"今日やること",sections:[{id:sid,name:"未分類",cards:[{id:uid(),type:"task",title:"タスク管理ンナーを使ってみる",content:"チェックで選択 → 完了ボタンで完了できます。",due:localDate(),tags:["サンプル"],color:"yellow",link:"",image:"",selected:false,createdAt:Date.now(),repeat:{type:"none",interval:1,weekdays:[]}}]}]},
  {id:uid(),name:"就職活動",sections:[{id:uid(),name:"応募・準備",cards:[]}]},
  {id:uid(),name:"AI制作",sections:[{id:uid(),name:"作りたいもの",cards:[]}]}
 ],archive:[],freeItems:[]}
}
function load(){try{const r=localStorage.getItem(STORAGE_KEY);return r?JSON.parse(r):defaultData()}catch{return defaultData()}}
let data=load();
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function board(){return data.boards.find(b=>b.id===data.selectedBoardId)||data.boards[0]}
function allCards(){return data.boards.flatMap(b=>b.sections.flatMap(s=>s.cards.map(c=>({...c,boardId:b.id,boardName:b.name,sectionId:s.id,sectionName:s.name}))))}
function findCard(id){for(const b of data.boards)for(const s of b.sections){const c=s.cards.find(x=>x.id===id);if(c)return{board:b,section:s,card:c}}}
function esc(v=""){return v.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function overdue(c){return c.due&&c.due<localDate()}
function showView(v){data.view=v;save();["today","home","board","archive","freeboard"].forEach(n=>els[n+"View"].classList.toggle("hidden",n!==v));renderAll()}
function renderAll(){applySettings();renderSidebar();if(data.view==="today")renderToday();if(data.view==="home")renderHome();if(data.view==="board")renderBoard();if(data.view==="archive")renderArchive();if(data.view==="freeboard")renderFreeboard()}
function applySettings(){document.body.dataset.theme=data.settings.theme;document.body.dataset.density=data.settings.density;document.documentElement.style.setProperty("--accent",data.settings.accent);els.themeSelect.value=data.settings.theme;els.accentColorInput.value=data.settings.accent;els.densitySelect.value=data.settings.density}
function renderSidebar(){els.boardList.innerHTML="";data.boards.forEach(b=>{const x=document.createElement("button");x.className="board-list-button"+(b.id===data.selectedBoardId&&data.view==="board"?" selected":"");x.textContent="📁 "+b.name;x.onclick=()=>{data.selectedBoardId=b.id;showView("board");els.sidebar?.classList.remove("open")};els.boardList.appendChild(x)})}

function renderHome(){const cs=allCards(),m=new Date().toISOString().slice(0,7);els.openTaskCount.textContent=cs.filter(c=>c.type==="task").length;els.todayTaskCount.textContent=cs.filter(c=>c.type==="task"&&c.due===localDate()).length;els.overdueCount.textContent=cs.filter(c=>c.type==="task"&&overdue(c)).length;els.monthlyDoneCount.textContent=data.archive.filter(a=>(a.completedAt||"").startsWith(m)).length;const up=cs.filter(c=>c.type==="task"&&c.due).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,8);els.upcomingList.innerHTML=up.length?up.map(c=>`<div class="upcoming-item"><span><strong>${esc(c.title)}</strong><br><small>${esc(c.boardName)} / ${esc(c.sectionName)}</small></span><span class="${overdue(c)?"due-chip overdue":"due-chip"}">${c.due}</span></div>`).join(""):"<p>期限付きタスクはありません。</p>"}
function renderToday(){const cs=allCards().filter(c=>c.type==="task"&&c.due===localDate());els.todayList.innerHTML=cs.length?cs.map(c=>`<article class="today-card"><span><strong>${esc(c.title)}</strong><br><small>${esc(c.boardName)} / ${esc(c.sectionName)}</small></span><button class="success-button" onclick="completeOneFromToday('${c.id}')">完了</button></article>`).join(""):"<p>今日のタスクはありません。</p>"}
window.completeOneFromToday=id=>completeCards([id]);

function renderBoard(){const b=board();els.currentBoardTitle.textContent=b.name;const tags=[...new Set(b.sections.flatMap(s=>s.cards.flatMap(c=>c.tags||[])))].sort(),cur=els.tagFilter.value;els.tagFilter.innerHTML=`<option value="">すべてのタグ</option>`+tags.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join("");els.tagFilter.value=tags.includes(cur)?cur:"";els.sectionBoard.innerHTML="";b.sections.forEach(s=>els.sectionBoard.appendChild(renderSection(s)));updateSelectionUI()}
function filtered(cards){const q=els.searchInput.value.trim().toLowerCase(),tag=els.tagFilter.value,status=els.statusFilter.value;let out=cards.filter(c=>{const hay=[c.title,c.content,c.link,...(c.tags||[])].join(" ").toLowerCase();if(q&&!hay.includes(q))return false;if(tag&&!(c.tags||[]).includes(tag))return false;if(status==="open"&&c.selected)return false;if(status==="selected"&&!c.selected)return false;if(status==="overdue"&&!overdue(c))return false;return true});const s=els.sortSelect.value;if(s==="dueAsc")out.sort((a,b)=>(a.due||"9999").localeCompare(b.due||"9999"));if(s==="dueDesc")out.sort((a,b)=>(b.due||"0000").localeCompare(a.due||"0000"));if(s==="createdDesc")out.sort((a,b)=>b.createdAt-a.createdAt);if(s==="createdAsc")out.sort((a,b)=>a.createdAt-b.createdAt);return out}
function renderSection(s){const w=document.createElement("section");w.className="board-section";const h=document.createElement("div");h.className="section-header";const t=document.createElement("h3");t.className="section-title";t.textContent=s.name;t.contentEditable=true;t.onblur=()=>{const v=t.textContent.trim();if(v){s.name=v;save()}else t.textContent=s.name};const a=document.createElement("div");a.className="section-actions";const add=document.createElement("button");add.textContent="＋ カード";add.onclick=()=>openCardModal(null,s.id);const del=document.createElement("button");del.textContent="削除";del.onclick=()=>deleteSection(s.id);a.append(add,del);h.append(t,a);const g=document.createElement("div");g.className="card-grid";g.dataset.sectionId=s.id;g.ondragover=e=>e.preventDefault();g.ondrop=e=>dropIntoSection(e,s.id);const cs=filtered([...s.cards]);if(cs.length)cs.forEach(c=>g.appendChild(renderCard(c,s.id)));else g.innerHTML=`<div class="empty-section">ここにカードを置けます。</div>`;w.append(h,g);return w}
function renderCard(c,sid){const x=document.createElement("article");x.className=`memo-card ${c.color||"white"}${c.selected?" selected":""}`;x.draggable=true;x.dataset.cardId=c.id;x.ondragstart=()=>{draggedCardId=c.id;x.classList.add("dragging")};x.ondragend=()=>x.classList.remove("dragging");x.ondragover=e=>{e.preventDefault();x.classList.add("drag-over")};x.ondragleave=()=>x.classList.remove("drag-over");x.ondrop=e=>dropOnCard(e,sid,c.id);const head=document.createElement("div");head.className="card-head";if(c.type==="task"){const ch=document.createElement("input");ch.type="checkbox";ch.className="card-select";ch.checked=!!c.selected;ch.onchange=()=>{c.selected=ch.checked;save();renderBoard()};head.append(ch)}else{const i=document.createElement("span");i.className="card-type";i.textContent=({memo:"📝",idea:"💡",link:"🔗",image:"🖼"}[c.type]||"📝");head.append(i)}const title=document.createElement("h3");title.className="card-title";title.textContent=c.title||"無題";head.append(title);x.append(head);if(c.image){const im=document.createElement("img");im.className="card-image";im.src=c.image;x.append(im)}if(c.content){const p=document.createElement("div");p.className="card-content";p.textContent=c.content;x.append(p)}if(c.link){const a=document.createElement("a");a.className="card-link";a.href=c.link;a.target="_blank";a.textContent=c.link;x.append(a)}const meta=document.createElement("div");meta.className="meta-row";if(c.due){const d=document.createElement("span");d.className="due-chip"+(overdue(c)?" overdue":"");d.textContent="期限 "+c.due;meta.append(d)}if(c.repeat?.type!=="none"){const r=document.createElement("span");r.className="repeat-chip";r.textContent=repeatLabel(c.repeat);meta.append(r)}if(meta.childNodes.length)x.append(meta);if((c.tags||[]).length){const tags=document.createElement("div");tags.className="tag-row";c.tags.forEach(t=>{const q=document.createElement("span");q.className="tag-chip";q.textContent="#"+t;tags.append(q)});x.append(tags)}const f=document.createElement("div");f.className="card-footer";const ed=document.createElement("button");ed.textContent="編集";ed.onclick=()=>openCardModal(c.id,sid);const de=document.createElement("button");de.textContent="削除";de.className="delete-card";de.onclick=()=>deleteCard(c.id);f.append(ed,de);x.append(f);return x}

function updateSelectionUI(){const n=allCards().filter(c=>c.type==="task"&&c.selected).length;els.selectionBar.classList.toggle("hidden",!n);els.completeSelectedButton.classList.toggle("hidden",!n);els.selectionCountText.textContent=`${n}件選択中`}
function clearSelection(){data.boards.forEach(b=>b.sections.forEach(s=>s.cards.forEach(c=>{if(c.type==="task")c.selected=false})));save();renderBoard()}
function completeSelected(){completeCards(allCards().filter(c=>c.type==="task"&&c.selected).map(c=>c.id))}
function completeCards(ids){if(!ids.length)return;let count=0;ids.forEach(id=>{const f=findCard(id);if(!f)return;const snap={...f.card,boardId:f.board.id,boardName:f.board.name,sectionName:f.section.name,completedAt:new Date().toISOString(),selected:false};data.archive.unshift(snap);const next=createNextRepeatCard(f.card);f.section.cards=f.section.cards.filter(c=>c.id!==id);if(next)f.section.cards.push(next);count++});save();toast(count);renderAll()}
function createNextRepeatCard(c){if(!c.repeat||c.repeat.type==="none")return null;return {...c,id:uid(),due:nextDue(c.due||localDate(),c.repeat),selected:false,createdAt:Date.now()}}
function nextDue(date,r){let d=new Date(date+"T00:00:00"),i=Math.max(1,+r.interval||1);if(r.type==="daily")d.setDate(d.getDate()+i);if(r.type==="weekly")d.setDate(d.getDate()+7*i);if(r.type==="monthly")d.setMonth(d.getMonth()+i);if(r.type==="weekdays"){const days=(r.weekdays||[]).map(Number);for(let o=1;o<=14;o++){const c=new Date(d);c.setDate(d.getDate()+o);if(days.includes(c.getDay()))return localDate(c)}}return localDate(d)}
function repeatLabel(r){if(r.type==="daily")return r.interval==1?"毎日":`${r.interval}日ごと`;if(r.type==="weekly")return r.interval==1?"毎週":`${r.interval}週ごと`;if(r.type==="monthly")return r.interval==1?"毎月":`${r.interval}か月ごと`;if(r.type==="weekdays"){const n=["日","月","火","水","木","金","土"];return "毎週 "+(r.weekdays||[]).map(x=>n[x]).join("・")}return ""}
function toast(count){const x=document.createElement("div");x.className="completion-toast";x.innerHTML=data.settings.theme==="dopaboy"?`CLEAR!<small>${count}件を「完了したこと」に保存</small>`:`✓ タスク完了<small>${count}件を「完了したこと」に保存しました</small>`;document.body.append(x);setTimeout(()=>x.remove(),1500)}

function addBoard(){const n=els.boardNameInput.value.trim();if(!n)return;const id=uid();data.boards.push({id,name:n,sections:[{id:uid(),name:"未分類",cards:[]}]});data.selectedBoardId=id;els.boardNameInput.value="";save();showView("board")}
function deleteBoard(){const b=board();if(data.boards.length===1)return alert("最後のボードは削除できません。");if(confirm(`「${b.name}」を削除しますか？`)){data.boards=data.boards.filter(x=>x.id!==b.id);data.selectedBoardId=data.boards[0].id;save();renderAll()}}
function addSection(){const n=prompt("小項目名","新しい小項目");if(n?.trim()){board().sections.push({id:uid(),name:n.trim(),cards:[]});save();renderBoard()}}
function deleteSection(id){const b=board(),s=b.sections.find(x=>x.id===id);if(!s)return;if(s.cards.length&&!confirm(`「${s.name}」と中のカードを削除しますか？`))return;b.sections=b.sections.filter(x=>x.id!==id);save();renderBoard()}
function deleteCard(id){const f=findCard(id);if(f&&confirm(`「${f.card.title}」を削除しますか？`)){f.section.cards=f.section.cards.filter(c=>c.id!==id);save();renderBoard()}}

function openCardModal(id=null,sid=null){editingCardId=id;editingImageData="";const b=board();els.cardSectionInput.innerHTML=b.sections.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");document.querySelectorAll(".weekday-input").forEach(x=>x.checked=false);if(id){const f=findCard(id),c=f.card;els.cardModalTitle.textContent="カードを編集";els.cardTypeInput.value=c.type;els.cardSectionInput.value=f.section.id;els.cardTitleInput.value=c.title||"";els.cardContentInput.value=c.content||"";els.cardDueInput.value=c.due||"";els.cardTagsInput.value=(c.tags||[]).join(", ");els.cardColorInput.value=c.color||"yellow";els.cardLinkInput.value=c.link||"";editingImageData=c.image||"";const r=c.repeat||{type:"none",interval:1,weekdays:[]};els.repeatTypeInput.value=r.type;els.repeatIntervalInput.value=r.interval||1;document.querySelectorAll(".weekday-input").forEach(x=>x.checked=(r.weekdays||[]).includes(+x.value))}else{els.cardModalTitle.textContent="カードを追加";els.cardTypeInput.value="task";els.cardSectionInput.value=sid||b.sections[0].id;els.cardTitleInput.value=els.cardContentInput.value=els.cardDueInput.value=els.cardTagsInput.value=els.cardLinkInput.value="";els.cardColorInput.value="yellow";els.repeatTypeInput.value="none";els.repeatIntervalInput.value=1}updateRepeatUI();updatePreview();els.cardModal.classList.remove("hidden")}
function updateRepeatUI(){const t=els.repeatTypeInput.value;els.repeatIntervalWrap.classList.toggle("hidden",t==="none"||t==="weekdays");els.weekdayPickerWrap.classList.toggle("hidden",t!=="weekdays")}
function saveCard(){const b=board(),title=els.cardTitleInput.value.trim(),content=els.cardContentInput.value.trim();if(!title&&!content&&!editingImageData)return alert("タイトル・内容・画像のどれかを入れてください。");const weekdays=[...document.querySelectorAll(".weekday-input:checked")].map(x=>+x.value);const cd={type:els.cardTypeInput.value,title:title||"無題",content,due:els.cardDueInput.value,tags:els.cardTagsInput.value.split(",").map(x=>x.trim()).filter(Boolean),color:els.cardColorInput.value,link:els.cardLinkInput.value.trim(),image:editingImageData,repeat:{type:els.repeatTypeInput.value,interval:Math.max(1,+els.repeatIntervalInput.value||1),weekdays}};if(editingCardId){const f=findCard(editingCardId);Object.assign(f.card,cd);if(f.section.id!==els.cardSectionInput.value){f.section.cards=f.section.cards.filter(c=>c.id!==editingCardId);b.sections.find(s=>s.id===els.cardSectionInput.value).cards.push(f.card)}}else b.sections.find(s=>s.id===els.cardSectionInput.value).cards.push({id:uid(),...cd,selected:false,createdAt:Date.now()});save();els.cardModal.classList.add("hidden");renderBoard()}
function dropIntoSection(e,sid){e.preventDefault();const f=findCard(draggedCardId),t=board().sections.find(s=>s.id===sid);if(!f||!t)return;f.section.cards=f.section.cards.filter(c=>c.id!==draggedCardId);t.cards.push(f.card);save();renderBoard()}
function dropOnCard(e,sid,targetId){e.preventDefault();e.stopPropagation();if(draggedCardId===targetId)return;const f=findCard(draggedCardId),t=board().sections.find(s=>s.id===sid);if(!f||!t)return;f.section.cards=f.section.cards.filter(c=>c.id!==draggedCardId);const i=t.cards.findIndex(c=>c.id===targetId);t.cards.splice(i,0,f.card);save();renderBoard()}

function renderArchive(){const q=els.archiveSearchInput.value.toLowerCase(),filter=els.archiveBoardFilter.value;const opts=[...new Map(data.archive.filter(a=>a.boardId).map(a=>[a.boardId,a.boardName]))];els.archiveBoardFilter.innerHTML=`<option value="">すべてのボード</option>`+opts.map(([id,n])=>`<option value="${id}">${esc(n)}</option>`).join("");els.archiveBoardFilter.value=filter;const items=data.archive.filter(a=>(!q||[a.title,a.content,a.boardName,...(a.tags||[])].join(" ").toLowerCase().includes(q))&&(!filter||a.boardId===filter));els.archiveList.innerHTML=items.length?items.map(a=>`<article class="archive-card"><h3>✅ ${esc(a.title)}</h3><p>${esc(a.content||"")}</p><p><small>${esc(a.boardName||"")} / ${esc(a.sectionName||"")}<br>${new Date(a.completedAt).toLocaleString("ja-JP")}</small></p><div class="archive-actions"><button class="secondary-button" onclick="restoreArchive('${a.id}')">戻す</button><button class="danger-outline-button" onclick="deleteArchive('${a.id}')">削除</button></div></article>`).join(""):"<p>完了したタスクはまだありません。</p>"}
window.restoreArchive=id=>{const a=data.archive.find(x=>x.id===id);if(!a)return;let b=data.boards.find(x=>x.id===a.boardId)||data.boards[0],s=b.sections.find(x=>x.name===a.sectionName)||b.sections[0];const r={...a,selected:false};["boardId","boardName","sectionName","completedAt"].forEach(k=>delete r[k]);s.cards.push(r);data.archive=data.archive.filter(x=>x.id!==id);save();renderArchive()}
window.deleteArchive=id=>{if(confirm("この完了記録を削除しますか？")){data.archive=data.archive.filter(x=>x.id!==id);save();renderArchive()}}

function renderFreeboard(){els.freeCanvas.innerHTML="";data.freeItems.forEach(i=>{const e=document.createElement("div");e.className=`free-item ${i.type==="image"?"free-image":"free-note"}`;e.style.left=i.x+"px";e.style.top=i.y+"px";if(i.type==="image")e.innerHTML=`<img src="${i.content}">`;else e.textContent=i.content;const d=document.createElement("button");d.className="free-delete";d.textContent="×";d.onclick=()=>{data.freeItems=data.freeItems.filter(x=>x.id!==i.id);save();renderFreeboard()};e.append(d);makeDrag(e,i);els.freeCanvas.append(e)})}
function makeDrag(e,i){let sx,sy,ox,oy,on=false;e.onpointerdown=v=>{if(v.target.tagName==="BUTTON")return;on=true;sx=v.clientX;sy=v.clientY;ox=i.x;oy=i.y};e.onpointermove=v=>{if(!on)return;i.x=Math.max(0,ox+v.clientX-sx);i.y=Math.max(0,oy+v.clientY-sy);e.style.left=i.x+"px";e.style.top=i.y+"px"};e.onpointerup=()=>{on=false;save()}}
function readImage(f,cb){if(!f)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
function updatePreview(){els.imagePreviewWrap.classList.toggle("hidden",!editingImageData);if(editingImageData)els.imagePreview.src=editingImageData}

els.addBoardButton.onclick=addBoard;els.boardNameInput.onkeydown=e=>{if(e.key==="Enter")addBoard()};els.todayButton.onclick=()=>showView("today");els.homeButton.onclick=()=>showView("home");els.archiveButton.onclick=()=>showView("archive");els.freeboardButton.onclick=()=>showView("freeboard");els.settingsButton.onclick=()=>els.settingsModal.classList.remove("hidden");els.addSectionButton.onclick=addSection;els.addCardButton.onclick=()=>openCardModal();els.completeSelectedButton.onclick=completeSelected;els.completeSelectedBarButton.onclick=completeSelected;els.clearSelectionButton.onclick=clearSelection;els.deleteBoardButton.onclick=deleteBoard;
[els.searchInput,els.tagFilter,els.statusFilter,els.sortSelect].forEach(x=>x.oninput=renderBoard);[els.archiveSearchInput,els.archiveBoardFilter].forEach(x=>x.oninput=renderArchive);els.saveCardButton.onclick=saveCard;els.repeatTypeInput.onchange=updateRepeatUI;els.cardImageInput.onchange=e=>readImage(e.target.files[0],d=>{editingImageData=d;updatePreview()});els.removeImageButton.onclick=()=>{editingImageData="";updatePreview()};document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>$(x.dataset.close).classList.add("hidden"));els.themeSelect.onchange=()=>{data.settings.theme=els.themeSelect.value;save();applySettings()};els.accentColorInput.oninput=()=>{data.settings.accent=els.accentColorInput.value;save();applySettings()};els.densitySelect.onchange=()=>{data.settings.density=els.densitySelect.value;save();applySettings()};els.mobileMenuButton.onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
els.addFreeNoteButton.onclick=()=>{const t=prompt("付箋に書く内容");if(t){data.freeItems.push({id:uid(),type:"note",content:t,x:40,y:40});save();renderFreeboard()}};els.freeImageInput.onchange=e=>readImage(e.target.files[0],d=>{data.freeItems.push({id:uid(),type:"image",content:d,x:60,y:60});save();renderFreeboard()});els.clearFreeboardButton.onclick=()=>{if(confirm("自由帳をすべて消しますか？")){data.freeItems=[];save();renderFreeboard()}};
els.exportButton.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`task-kanrinner-${localDate()}.json`;a.click();URL.revokeObjectURL(u)};
els.importInput.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();renderAll();alert("読み込みました。")}catch{alert("読み込めないファイルです。")}};r.readAsText(f)};
renderAll();
